# [START runtime]
runtime: nodejs12
env: standard
instance_class: F1
automatic_scaling:
  max_instances: 10
  min_instances: 0
# [END runtime]


# [START handlers]
handlers:
  - url: /static
    static_dir: public/static

  - url: /(.*\.(json|ico|js))$
    static_files: public/\1
    upload: public/.*\.(json|ico|js)$

  - url: .*
    static_files: public/index.html
    upload: public/index.html
# [END handlers]
